app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', 'WelcomeController@index');

// Route::get('home', 'HomeController@index');

// Route::controllers([
// 	'auth' => 'Auth\AuthController',
// 	'password' => 'Auth\PasswordController',
// ]);

Route::get('/', 'TaskController@index');

Route::resource('task','TaskController');

app/Models/Task.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model {

	protected $table = 'tasks';
	protected $fillable = ['title','description','done'];

	public static function addTask($input)
	{
		$response = array();

		$task = Task::create($input);
		
		$response['message'] = 'Task created';
		$response['error'] = false;
		$response['data'] = $task;

		return $response;
	}

	public static function getOrderedTasks()
	{
		$tasks = \DB::table('tasks')
			->orderBy('done','ASC')
			->orderBy('created_at','ASC')
			->get();
		return $tasks;
	}

}

app/Models/User.php
<?php namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/Http/Controllers/Controller.php
<?php namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesCommands;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController {

	use DispatchesCommands, ValidatesRequests;

}

app/Http/Controllers/HomeController.php
<?php namespace App\Http\Controllers;

class HomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('home');
	}

}

app/Http/Controllers/TaskController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$tasks = Task::getOrderedTasks();
		return view('tasks.index', array('tasks' => $tasks));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$task = new Task;
		return view('tasks.create', array('task' => $task));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$input = $request->only('title','description','done');

		// if(isset($input->done)){
		// 	$input->done = '1';
		// }else{
		// 	$input->done = '0';
		// }

		$response = Task::addTask($input);

		if($response['error'] == true){
			return redirect('task/create')->withErrors($response['message'])->withInput();
		}else{
			return redirect('task'); 
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$task = Task::find($id);
		return view('tasks.show', array('task' => $task));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$task = Task::find($id);
		return view('tasks.edit', array('task' => $task));
		// return view('tasks.edit', ['id' => $id]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$task = Task::find($id);
		$task->title = $request->title;
		$task->description = $request->description;
		$task->done = $request->done;
		$task->save();
		return redirect('task/'.$id); 
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$task = Task::find($id);
		$task->delete();
		return redirect('/');
	}

}

app/Http/Controllers/WelcomeController.php
<?php namespace App\Http\Controllers;

class WelcomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Welcome Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders the "marketing page" for the application and
	| is configured to only allow guests. Like most of the other sample
	| controllers, you are free to modify or remove it as you desire.
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('guest');
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('welcome');
	}

}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	{!! Html::style('css/app.css') !!}

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Laravel</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="/">Home</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="/auth/login">Login</a></li>
						<li><a href="/auth/register">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="/auth/logout">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>TODO list</title>

	{!! Html::style('css/app.css') !!}

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			@yield('content')
		</div>
	</div>
	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/tasks/create.blade.php
@extends('layout')
@section('content')
<div class="col-md-6 col-md-offset-3">
	<div class="page-header"><h1>Create a task</h1></div>
	<div class="panel-body">
		{!! Form::open(array('route' => 'task.store', 'class' => 'form-horizontal')) !!}
			
			@include('tasks.form')

		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layout')
@section('content')
<div class="col-md-6 col-md-offset-3">
	<div class="page-header"><h1>Edit task</h1></div>
	<div class="panel-body">
		{!! Form::open(array('action' => array('TaskController@update', $task->id), 'method' => 'PUT', 'class' => 'form-horizontal')) !!}
			
			@include('tasks.form',$task)

		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/tasks/form.blade.php
<div class="form-group">
	<label for="title">Title</label>
	{!! Form::text('title', $task->title, $attributes = array('class' => 'form-control')) !!}
</div>
<div class="form-group">
	<label for="description">Description</label>
	{!! Form::textarea('description', $task->description, $attributes = array('class' => 'form-control')) !!}
</div>
<div class="form-group">
	<label for="status">Status: </label>
	{!! Form::select('done', array(0 => 'Pending', 1 => 'Done'), $task->done) !!}
</div>
<!-- <div class="checkbox">
	<label for="status">
		{!! Form::checkbox('done', $task->done) !!} Done
	</label>
</div> -->
<!-- <br> -->
<div class="form-group">
	{!! Form::submit('Send', $attributes = array('class' => 'btn btn-primary')) !!}
	<a href=" {{ route('task.index') }} " class="btn btn-default" role="button">Back to Index</a>
</div>

resources/views/tasks/index.blade.php
@extends('layout')
@section('content')
<div class="col-md-10 col-md-offset-1">
	<div class="page-header"><h1>Index</h1></div>

	<a href="task/create" class="btn btn-default" ole="button">Create task</a><br><br>

	<div class="panel panel-default">
		<div class="panel-heading"><h4>List of tasks</h4></div>
		<!-- <div class="panel-body"> -->
		<table class="table table-hover">
			<thead><tr>
				<th>Title</th>
				<th>Status</th>
				<th>Created at</th>
				<th>Updated at</th>
				<th></th>
			</tr></thead>
			<tbody>
			@foreach($tasks as $t)
		    	<tr>
		    		<td> {{ $t->title }} </td>
		    		@if($t->done == true)
		    			<td> Done </td>
		    		@else
		    			<td>Pending</td>
		    		@endif
		    		<td> {{ $t->created_at }} </td>
		    		<td> {{ $t->updated_at }}</td>
		    		<td> <a href="{{ route('task.show', $t->id) }}">Show</a> </td>
		    		<!--<td> <a href="{{ route('task.destroy', $t->id, ['method' => 'DELETE']) }}">Delete</a> </td>-->
		    	</tr>
		  	@endforeach
			</tbody>
		</table>
		<!-- </div> -->
	</div>
	<script type="text/javascript">
		$('.btn-default').click(function(){
			alert('asd');
		});
	</script>
</div>
@endsection

resources/views/tasks/show.blade.php
@extends('layout')

@section('content')
<div class="col-md-6 col-md-offset-3">
	<div class="page-header"><h1>Task description</h1></div>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title"> {{ $task->title }} </h3>
		</div>
		<div class="panel-body">
			{{ $task->description }}
		</div>
	</div>
	<div class="form-group">
		Status:
		@if($task->done == true)
			<span class="label label-success">Done</span>
		@else
			<span class="label label-warning">Pending</span>
		@endif
	</div>

	<a href=" {{ route('task.edit', $task->id) }} " class="btn btn-primary btn-block" role="button">Edit</a>

	{!! Form::open(array('action' => array('TaskController@destroy', $task->id), 'method' => 'DELETE')) !!}
		{!! Form::submit('Delete', $attributes = array('class' => 'btn btn-danger btn-block')) !!}
	{!! Form::close() !!}

	<a href=" {{ route('task.index') }} " class="btn btn-default btn-block" role="button">Back to Index</a>
	
</div>
@endsection